### ISSUE TITLE
Hallway UX tests for <vaadin-password-field>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#107]
Plan, conduct and report

**Comment by samiheikki** [comment]
Plan: https://docs.google.com/a/vaadin.com/document/d/1ZPcj61NpGUY7acLszbLKVP_CJqa2JdjYuT_sgOBKUTM/edit?usp=sharing

**Comment by samiheikki** [comment]
Summary:
- Element is easy to use when typing a password
- When the password-field text is not visible => iPhone shows lowercase keyboard. When the password-field text is visible => iPhone shows uppercase keyboard (for the first letter). **Inconsistent**
- Mobile or desktop Safari doesn’t have “Suggest password” (based on your saved passwords) as native password input has. (Test was provided in http and not https-address, so might be because of that).
- Eye button is hard to click on mobile (At least on iPhone 5s & iPhone 6s)
- In “Skype’s mobile safari” it was possible to set focusring in all of the fields (but not possible on native mobile safari).

Full test report: https://docs.google.com/document/d/1ZPcj61NpGUY7acLszbLKVP_CJqa2JdjYuT_sgOBKUTM/edit#heading=h.w52594qstpox

**Comment by gatanaso** [comment]
#114

**Comment by gatanaso** [comment]
Improved password-field eye-button clickability #114
