### ISSUE TITLE
Reveal button should not cause the viewport to jump unexpectedly up and down (iPhone issue)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field#193]
When the icon gets clicked, the screen scrolls unexpectedly

**Comment by jouni** [comment]
The field should still get focused, as otherwise there’s the possibility that the unmasked password will remain visible. We specifically wanted the field to get focused, as the password is automatically masked when the field is blurred.

Try to fix the scrolling issue instead. If that becomes too complex to solve, we can evaluate if it is acceptable to leave the password unmasked on iOS. It might be okay, as those devices are quite personal and it’s not as easy to spy the users screen.

**Comment by web-padawan** [comment]
@jouni most of the existing solutions used to prevent scroll rely on doing weird tricks with the `document.body`. See https://stackoverflow.com/questions/37287148/ios-safari-chrome-unwanted-scrolling-when-focusing-an-input-inside-the-modal

I'm not sure if we want something like this to be implemented inside of the particular component.

**Comment by jouni** [comment]
This is a different problem than what is described in that issue.

I suppose Tomi understood the problem incorrectly. The field should be focused, but the viewport should not jump unexpectedly up and down, but rather scroll the field into the center of the viewport like is done when the field is normally focused.

Here’s the problem:
![password-field-jumpy](https://user-images.githubusercontent.com/66382/37461475-24b1363a-2857-11e8-9e50-531d9e0771be.gif)

And here’s how it should work – here I’m tapping the field first and then the reveal button, but it should work the same if I just tapped the reveal button:
![password-field-no-jumpy](https://user-images.githubusercontent.com/66382/37461532-46981962-2857-11e8-84b8-96c123330eb4.gif)

**Comment by web-padawan** [comment]
@jouni prototyped the fix in the fix/reveal-button-scroll-ios branch, this worked in simulator as you described in the above comment. Will also verify with the real device and submit a RP if that works.
