### ISSUE TITLE
vaadin-number-field step up/down buttons don't work with some values

### ISSUE THREAD

**Issue by IrenBereczki** [vaadin/vaadin-text-field#395]
Vaadin Number Field increment number suddenly stops. The bug is in version number 13.0.8 if I revert back to version 13.0.1 it all works fine. I have attached a document with more details and some screenshots with examples.
[Vaadin Number Field Bug.docx](https://github.com/vaadin/flow/files/3346189/Vaadin.Number.Field.Bug.docx)

**Comment by Haprog** [comment]
Same issue doesn't seem to happen with the demo for v2.3.5 but happens with v2.3.6 so it seems to be a bug introduced in v2.3.6.

**Comment by Haprog** [comment]
Verified that it was still working at commit 79d87d7 (1 commit after v2.3.5), but got broken by commit 7609100 (2 commits after v2.3.5).

The problem seems to be that the new `_getMultiplier(number)` method added in https://github.com/vaadin/vaadin-text-field/commit/7609100a9e936ea650ddcc3501756a6b1ceb4ce3#diff-5aaf62201e3c9943b6ef2aa8af27f613R263 is actually causing the problem it's trying to avoid.

E.g. the calculation `1.001 * 1000` results in `1000.9999999999999` in JS but `_getMultiplier` expects that to return `1001`. The result is that `_getMultiplier(1.001)` returns `10000000000000000` which is actually bigger than `Number.MAX_SAFE_INTEGER` (which equals `9007199254740991`) so we hit the JS number precision issue anyway.

**Comment by Haprog** [comment]
Another fun example:
```js
5.1 * 10;      // = 51
5.1 * 10 * 10; // = 510
5.1 * 100;     // = 509.99999999999994
```
