### ISSUE TITLE
JAWS/NVDA - required text field pronounced as "invalid"

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-text-field#456]
@limonte commented on [Fri May 04 2018](https://github.com/vaadin/vaadin-core-elements-ux/issues/3)

**Expected:** "First Name required entry type text"

**Actual:** "First Name required **invalid** entry type text"

The same issue applies for other text fields - Last Name, Email

JAWS latest 2018.1802.78

**Comment by anezthes** [comment]
From https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/

> Please note that when a required attribute is used on a form control screen reader announces that field is required and also invalid. Once the form field is filled, the “invalid” notification will not be announced to screen reader.

> Similar to the“required” attribute in HTML5, WAI-ARIA introduced the “aria-required” attribute. If this attribute is used on a form control it will be exposed as required by assistive technologies.

**Comment by anezthes** [comment]
Works as expected in Chrome and Safari with VoiceOver.

We _could_ consider using "aria-required" instead if it results in a more preferable experience. However, "required" is most likely the safer option moving forward since it is part of HTML5.

This article is from February 2019, but still might be worth checking out:
https://developer.paciellogroup.com/blog/2019/02/required-attribute-requirements/

**Comment by rolfsmeds** [comment]
Closing, as this is just the way JAWS and NVDA handle required fields, not an issue with our component.
